// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxSoCBhtQHC2cSx7KXPybdQs1ElL-S7sg',
    appId: '1:80070862600:web:18dc745ab377b4764c6ebd',
    messagingSenderId: '80070862600',
    projectId: 'profile-demo-53d30',
    authDomain: 'profile-demo-53d30.firebaseapp.com',
    storageBucket: 'profile-demo-53d30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7guDwPAZ8K5NbFr12J0AUPadSEW-J9c',
    appId: '1:80070862600:android:f53180f8658d69d64c6ebd',
    messagingSenderId: '80070862600',
    projectId: 'profile-demo-53d30',
    storageBucket: 'profile-demo-53d30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMzr_1m8peskwcF-PCcbnRbBmTQ4xQgs',
    appId: '1:80070862600:ios:e1314f2e59a339df4c6ebd',
    messagingSenderId: '80070862600',
    projectId: 'profile-demo-53d30',
    storageBucket: 'profile-demo-53d30.appspot.com',
    iosBundleId: 'com.example.profileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMzr_1m8peskwcF-PCcbnRbBmTQ4xQgs',
    appId: '1:80070862600:ios:8903d9fb7ef791ae4c6ebd',
    messagingSenderId: '80070862600',
    projectId: 'profile-demo-53d30',
    storageBucket: 'profile-demo-53d30.appspot.com',
    iosBundleId: 'com.example.profileApp.RunnerTests',
  );
}
